version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn yourprojectname.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    restart: always
